# Generated by Django 2.2 on 2020-05-22 18:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_dairy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('price', models.IntegerField(default=0)),
                ('quantity', models.FloatField(default=0.0, max_length=10)),
                ('total', models.FloatField(default=0.0, max_length=10)),
                ('related_customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CustomerLedger', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
