# Generated by Django 3.0.6 on 2020-05-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dairy', '0002_customerledger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerledger',
            name='date',
            field=models.DateField(),
        ),
    ]
