# Generated by Django 3.0.6 on 2020-05-29 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dairy', '0003_auto_20200529_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerledger',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
