# Generated by Django 3.0.6 on 2020-05-30 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_dairy', '0008_auto_20200530_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerledger',
            name='related_customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
